In [3]:
import pandas as pd
import numpy as np
import names
import random

In [8]:
n = 40

names_generated = []
values_generated = []
groups_generated = []

groups_values = ["PLACEBO", "EXPERIMENTAL"]
mu_exp, sigma_exp = 12, 3
mu_placebo, sigma_placebo = 20, 5

for i in range(n):
    name = names.get_full_name()
    group = random.choice(groups_values)
    if group == groups_values[1]:
        value = int(np.random.normal(mu_exp, sigma_exp, 1)[0])
    else:
        value = int(np.random.normal(mu_placebo, sigma_placebo, 1)[0])
    names_generated.append(name)
    groups_generated.append(group)
    values_generated.append(value)


print(groups_generated, values_generated, names_generated)

['EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'PLACEBO', 'PLACEBO', 'EXPERIMENTAL', 'PLACEBO', 'PLACEBO', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'PLACEBO', 'EXPERIMENTAL', 'PLACEBO', 'EXPERIMENTAL', 'PLACEBO', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'PLACEBO', 'PLACEBO', 'EXPERIMENTAL', 'PLACEBO', 'EXPERIMENTAL', 'PLACEBO', 'PLACEBO', 'EXPERIMENTAL', 'PLACEBO', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'EXPERIMENTAL', 'PLACEBO', 'PLACEBO'] [12, 11, 15, 11, 11, 26, 19, 11, 21, 22, 7, 15, 7, 12, 10, 10, 15, 27, 14, 22, 13, 14, 6, 10, 10, 19, 27, 12, 19, 14, 15, 23, 12, 17, 13, 13, 13, 4, 17, 26] ['Brian Stone', 'Joshua Thompson', 'Kenneth Craycraft', 'Beth Wolfe', 'Tom Short', 'Richard Hughes', 'Reggie Smith', 'Pearl Willemsen', 'Wanda Green', 'Kristen Brereton', 'Lana White', 'Morris Harris', 'Leah Ray', 'Jennifer Argo', 'Judy Mullen', 'Joie Riddick', 'Flor Squires', 'Barbara Chua', 'Jacqueline Gullatt', 'Kelvin Smith', 'Janet Cohen', 'Tracey Bland', 'Frederick Silva', 'Maria Howard', 'Jane Davenport', 'Hattie Rumley', 'Rachel Morris', 'Steven James', 'Molly Mosley', 'Clayton Gibbs', 'Jessi Parrish', 'Matt Pennington', 'Francis Buco', 'Louis Sparks', 'John Brown', 'Charles Yerkey', 'Alice Yarbrough', 'John Cox', 'Lester Dowling', 'Keith Smith']

In [14]:

arr = [[names_generated[i], values_generated[i], groups_generated[i]] for i in range(n)]
df = pd.DataFrame(data=arr, columns=["nombre", "dias_hospitalizacion", "grupo"])
df

                nombre  dias_hospitalizacion         grupo
0          Brian Stone                    12  EXPERIMENTAL
1      Joshua Thompson                    11  EXPERIMENTAL
2    Kenneth Craycraft                    15  EXPERIMENTAL
3           Beth Wolfe                    11  EXPERIMENTAL
4            Tom Short                    11  EXPERIMENTAL
5       Richard Hughes                    26       PLACEBO
6         Reggie Smith                    19       PLACEBO
7      Pearl Willemsen                    11  EXPERIMENTAL
8          Wanda Green                    21       PLACEBO
9     Kristen Brereton                    22       PLACEBO
10          Lana White                     7  EXPERIMENTAL
11       Morris Harris                    15  EXPERIMENTAL
12            Leah Ray                     7  EXPERIMENTAL
13       Jennifer Argo                    12  EXPERIMENTAL
14         Judy Mullen                    10  EXPERIMENTAL
15        Joie Riddick                    10  EXPERIMENTAL
16        Flor Squires                    15  EXPERIMENTAL
17        Barbara Chua                    27       PLACEBO
18  Jacqueline Gullatt                    14  EXPERIMENTAL
19        Kelvin Smith                    22       PLACEBO
20         Janet Cohen                    13  EXPERIMENTAL
21        Tracey Bland                    14       PLACEBO
22     Frederick Silva                     6  EXPERIMENTAL
23        Maria Howard                    10  EXPERIMENTAL
24      Jane Davenport                    10  EXPERIMENTAL
25       Hattie Rumley                    19       PLACEBO
26       Rachel Morris                    27       PLACEBO
27        Steven James                    12  EXPERIMENTAL
28        Molly Mosley                    19       PLACEBO
29       Clayton Gibbs                    14  EXPERIMENTAL
30       Jessi Parrish                    15       PLACEBO
31     Matt Pennington                    23       PLACEBO
32        Francis Buco                    12  EXPERIMENTAL
33        Louis Sparks                    17       PLACEBO
34          John Brown                    13  EXPERIMENTAL
35      Charles Yerkey                    13  EXPERIMENTAL
36     Alice Yarbrough                    13  EXPERIMENTAL
37            John Cox                     4  EXPERIMENTAL
38      Lester Dowling                    17       PLACEBO
39         Keith Smith                    26       PLACEBO

In [13]:
df.to_csv("estudio.csv", sep=";")